default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweeeterapp_development

test:
  <<: *default
  database: tweeeterapp_test

production:
  <<: *default
  database: tweeeterapp_production
  username: tweeeterapp
  password: <%= ENV['TWEEETERAPP_DATABASE_PASSWORD'] %>
